# Generated by Django 3.0.3 on 2020-08-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200807_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_id',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
