# Generated by Django 3.0.3 on 2020-08-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200807_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=6),
            preserve_default=False,
        ),
    ]
