# Generated by Django 3.0.3 on 2020-08-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200807_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengeraccount',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='passengeraccount',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
